---
- name: Create Management AVNs
  hosts: localhost
  vars_files:
    - vars/management_domain_avns.yml
  roles:
    - role: create_avns
      # vars:
      #   create_management_avns_sddc_manager_ip: "{{ sddc_manager_ip }}"
      #   create_management_avns_sddc_manager_username: "{{ sddc_manager_username }}"
      #   create_management_avns_sddc_manager_password: "{{ sddc_manager_password }}"
      #   create_management_avns_sddc_management_domain_payload: "{{ avns_payload }}"
      #   create_management_avns_nsxt_edge_name: "{{ management_edge_cluster_name }}"