---
- name: Create SDDC Management Domain
  hosts: localhost
  vars_files:
    - vars/managment_domain.yml
  roles:
    - role: create_management_domain
      vars:
        create_management_domain_cloud_builder_ip: "{{ cloud_builder_ip }}"
        create_management_domain_cloud_builder_username: "{{ cloud_builder_username }}"
        create_management_domain_cloud_builder_password: "{{ cloud_builder_password }}"
        create_management_domain_sddc_management_domain_payload: "{{ sddc_management_domain_payload }}"