  - name: Create SDDC management Domain Validation
    cloud_builder_sddc_validation:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_management_domain_payload: "{{ sddc_management_domain_payload }}"
    register: result

  - set_fact:
      sddc_id: "{{ result.meta.id }}"
  
  - debug:
      msg: "SDDC management Domain ID: {{ sddc_id }}"

  - name: Get SDDC management Domain Validation Statuss
    cloud_builder_validation_status:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_id: "{{ sddc_id }}"
    register: result

  - debug:
      msg: "Current execution status: {{ result }}"
  - name: Wait Until SDDC management Domain Validation is Completed
    cloud_builder_validation_status:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_id: "{{ sddc_id }}"
    register: result
    until: result.meta.executionStatus == "COMPLETED" or result.meta.executionStatus == "FAILED"
    retries: 60 
    delay: 30
    failed_when: result.meta.executionStatus == "FAILED"

  - debug:
      msg: "Current execution status: {{ result.meta.executionStatus }}"
  
  - debug:
      msg: "Creating management Domain"

  - name: Create SDDC management Domain 
    cloud_builder_create_management_domain:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_management_domain_payload: "{{ sddc_management_domain_payload }}"
    register: result
      
  - set_fact:
      sddc_id: "{{ result.meta.id }}"
  
  - debug:
      msg: "SDDC management Domain ID: {{ sddc_id }}"

  - name: Wait Until SDDC management Domain is Completed
    cloud_builder_management_bring_up_status:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_id: "{{ sddc_id }}"
    register: sddc_management_domain
    until: sddc_management_domain.meta.status == "COMPLETED_WITH_SUCCESS" or sddc_management_domain.meta.status == "COMPLETED_WITH_FAILURE"  
    retries: 60
    delay: 30
    failed_when:  sddc_management_domain .meta.status == "COMPLETED_WITH_FAILURE"  

  - debug:
      msg: "SDDC management Domain : {{ sddc_management_domain.meta  }}"
  - debug:
      msg: "SDDC management Domain ID: {{ sddc_management_domain.meta.id  }} Has Completed With Success"
