  - name: Create SDDC Managment Domain Validation
    cloud_builder_sddc_validation:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_management_domain_payload: "{{ sddc_management_domain_payload }}"
    register: result
      
  - set_fact:
      sddc_id: "{{ result.meta.id }}"
  
  - debug:
      msg: "SDDC Managment Domain ID: {{ sddc_id }}"

  - name: Get SDDC Managment Domain Validation Status
    cloud_builder_get_validation_status:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_id: "{{ sddc_id }}"
    register: result

  - debug:
      var: result

  - name: Wait Until SDDC Managment Domain Validation is Completed
    cloud_builder_get_validation_status:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_id: "{{ sddc_id }}"
    register: result
    until: result.meta.executionStatus == "COMPLETED"
    retries: 60
    delay: 30

  - debug:
      msg: "Creating Managment Domain"

  - name: Create SDDC Managment Domain Validation
    cloud_builder_create_managment_domain:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_management_domain_payload: "{{ sddc_management_domain_payload }}"
    register: result
      
  - set_fact:
      sddc_id: "{{ result.meta.id }}"
  
  - debug:
      msg: "SDDC Managment Domain ID: {{ sddc_id }}"

  - name: Wait Until SDDC Managment Domain Validation is Completed
    cloud_builder_managment_domain_build:
      cloud_builder_ip: "{{ cloud_builder_ip }}"
      cloud_builder_user: "{{ cloud_builder_username }}"
      cloud_builder_password: "{{ cloud_builder_password }}"
      sddc_id: "{{ sddc_id }}"
    register: sddc_managment_domain
    until: sddc_managment_domain.meta.status == "COMPLETED_WITH_SUCCESS"
    retries: 60
    delay: 30

  - debug:
      msg: "SDDC Managment Domain ID: {{ sddc_managment_domain.meta.id  }} Has Completed With Success"
