---
- name: Validate AVNs
  sddc_manager_avns:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"
    sddc_manager_password: "{{ sddc_manager_password }}"
    avns_payload: "{{ avns_payload }}"
    management_edge_cluster_name: "{{ management_edge_cluster_name }}"
    operation: validate
  register: result

- name: Check if task completed
  debug:
    msg: "Task completed"
  when: result.meta.executionStatus == 'COMPLETED'
- set_fact:
    task_id: "{{ result.meta.id }}"
- name: Debug output
  debug:
    var: result

# - name: Monitor tasks
#   sddc_manager_tasks_status:
#     sddc_manager_ip: "{{ sddc_manager_ip }}"
#     sddc_manager_user: "{{ sddc_manager_username }}"
#     sddc_manager_password: "{{ sddc_manager_password }}"
#     sddc_manager_tasks_type: avns
#     validate: True
#   register: result
#   until: result.meta.executionStatus == 'COMPLETED'
#   retries: 60
#   delay: 10
#   failed_when: result.meta.executionStatus == "FAILED"


# - name: Create AVNs
#   sddc_manager_avns:
#     sddc_manager_ip: "{{ sddc_manager_ip }}"
#     sddc_manager_user: "{{ sddc_manager_user }}"
#     sddc_manager_password: "{{ sddc_manager_password }}"
#     avns_payload: "{{ avns_payload }}"
#   when: result is succeeded