---
- name: Validate AVNs
  sddc_manager_avns:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"
    sddc_manager_password: "{{ sddc_manager_password }}"
    avns_payload: "{{ avns_payload }}"
    management_edge_cluster_name: "{{ management_edge_cluster_name }}"
    operation: validate
  register: result

- name: Check if task completed
  debug:
    msg: "Task completed"
  when: result.meta.executionStatus == 'COMPLETED'
- set_fact:
    task_id: "{{ result.meta.id }}"
- name: Debug output
  debug:
    var: result


- name: Validate AVNs
  sddc_manager_avns:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"
    sddc_manager_password: "{{ sddc_manager_password }}"
    avns_payload: "{{ avns_payload }}"
    management_edge_cluster_name: "{{ management_edge_cluster_name }}"
    operation: create
  register: result

- set_fact:
    task_id: "{{ result.meta.id }}"
- name: Debug output
  debug:
    var: result
    
- name: Wait for AVNs to be ready
  sddc_manager_tasks_status:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"
    sddc_manager_password: "{{ sddc_manager_password }}"
    tasks_id: "{{ task_id }}"
    sddc_manager_tasks_type: avns
    validation: False
  register: result
  until: result.meta.status == 'Successful'
  retries: 60
  delay: 10
  failed_when: result.meta.status == "FAILED"

- debug:
    msg: "NSX AVNs Created"