---
- name: Validate AVNs
  sddc_manager_avns:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"
    sddc_manager_password: "{{ sddc_manager_password }}"
    avns_payload: "{{ avns_payload }}"
    management_edge_cluster_name: "{{ management_edge_cluster_name }}"
    operation: validate
  register: avn_validation_response

- name: Check task execution status
  block:
    - name: Debug success message
      debug:
        msg: "Task {{ avn_validation_response.meta.resultStatus }}"
      when: avn_validation_response.meta.resultStatus == 'SUCCEEDED'

    - name: Fail the task if execution status is FAILED
      fail:
        msg: "Task execution failed"
      when: avn_validation_response.meta.executionStatus == 'FAILED'
  when: avn_validation_response.meta.resultStatus in ['SUCCEEDED', 'FAILED']
  
- name: Create AVNs 
  sddc_manager_avns:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"  # Ensure consistent variable naming
    sddc_manager_password: "{{ sddc_manager_password }}"
    avns_payload: "{{ avns_payload }}"
    management_edge_cluster_name: "{{ management_edge_cluster_name }}"
    operation: create
  register: avns_created_response

- name: Debug output
  debug:
    var: avns_created_response
    
- name: Check AVNs Creation Status
  sddc_manager_tasks_status:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"
    sddc_manager_password: "{{ sddc_manager_password }}"
    tasks_id: "{{ avns_created_response.id }}"  # Assuming task_id comes from avns_created_response
    sddc_manager_tasks_type: avns
    validation: False
  register: avns_created_tasks_status
  until: avns_created_tasks_status.meta.status in ['Successful', 'Failed']  # Simplified condition
  retries: 60
  delay: 10
  failed_when: avns_created_tasks_status.meta.status == "Failed"  # Consistent error handling

- debug:
    msg: "NSX AVNs Created"
  when: avns_created_tasks_status.meta.status == "Successful"  # Explicit success message condition