---
- name: Create SDDC Managment Domain Validation
  sddc_manager_nsxt_edge_cluster:
    sddc_manager_ip: "{{ sddc_manager_ip }}"
    sddc_manager_user: "{{ sddc_manager_username }}"
    sddc_manager_password: "{{ sddc_manager_password }}"
    management_cluster_name: "{{ management_cluster_name }}"
    edge_cluster_payload: "{{ edge_cluster_payload }}"
    state: create
    validate: True
  register: result
    
- set_fact:
    edge_cluster_validation_id: "{{ result.meta.id }}"

- debug:
    msg: "Edge Cluster Validation ID: {{ edge_cluster_validation_id }}"

# - name: Wait for Edge Cluster to be ready
#   sddc_manager_tasks_status:
#     sddc_manager_ip: "{{ sddc_manager_ip }}"
#     sddc_manager_user: "{{ sddc_manager_username }}"
#     sddc_manager_password: "{{ sddc_manager_password }}"
#     task_id: "{{ edge_cluster_validation_id }}"
#     sddc_manager_tasks_type: nsxt_edge_cluster
#     validation: True
#   register: result
#   until: result.result.executionStatus == 'COMPLETED'
#   retries: 60
#   delay: 10